### ISSUE TITLE
Link for "4-Minute Guide to Debugging with Pry by Dick Ward" is broken

### ISSUE THREAD

**Issue by ddeleon267** [learn-co-curriculum/debugging-practice-using-pry#1]
The link given is: https://medium.com/@TheDickWard/an-intro-to-ruby-debugging-featuring-pry-c931fde6906

It's missing a 9 at the end; should be: https://medium.com/@TheDickWard/an-intro-to-ruby-debugging-featuring-pry-c931fde69069

**Comment by sgharms** [comment]
Corrected!
